services:
  pgrstwatch:
    profiles:
      - api
    image: python:3.12-slim # migrate to ghcr.io/astral-sh/uv:python3.12-trixie-slim
    working_dir: /app
    volumes:
      - .:/app:rw
      - ../../../src/infdb_package:/app/mnt/infdb_package
      - ../../../configs/:/app/mnt/configs-infdb #:ro # for *.yml configs and generated files
      - ./configs:/app/configs #:ro # for configs
    environment:
      - PYTHONUNBUFFERED=1
      - SERVICES_POSTGRES_DB=${SERVICES_POSTGRES_DB}
      - SERVICES_POSTGRES_USER=${SERVICES_POSTGRES_USER}
      - SERVICES_POSTGRES_PASSWORD=${SERVICES_POSTGRES_PASSWORD}
      - SERVICES_POSTGRES_EPSG=${SERVICES_POSTGRES_EPSG}
      - SERVICES_POSTGRES_HOST=${SERVICES_POSTGRES_HOST}
      - SERVICES_POSTGRES_EXPOSED_PORT=${SERVICES_POSTGRES_EXPOSED_PORT}
      - SERVICES_POSTGREST_EXPOSED_PORT=${SERVICES_POSTGREST_PORT}
    command:
      - /bin/sh
      - -lc
      - >
        python -m pip install --no-cache-dir /app/mnt/infdb_package psycopg[binary] pyyaml && echo "[pgrstwatch] starting" && exec python -u /app/watch_and_update_postgrest_conf.py
    healthcheck:
      test: [ "CMD-SHELL", "test -s /app/postgrest.conf" ]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 90s
    restart: unless-stopped
    networks:
      - infdb_network

  postgrest:
    profiles:
      - api
    image: postgrest/postgrest:latest
    command:
      - postgrest
      - /app/postgrest.conf
    volumes:
      - .:/app:ro # read-only is fine for PostgREST
    ports:
      - "${SERVICES_POSTGREST_PORT}:${SERVICES_POSTGREST_PORT}"
    depends_on:
      pgrstwatch:
        condition: service_healthy
    networks:
      - infdb_network
