services:
    choose-a-name:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ${CONFIG_INFDB_PATH}:/app/mnt/configs-infdb #:ro # for *.yml configs and generated files
            - ./configs:/app/configs #:ro # for configs
            - .:/app/ #:ro # for source code # for development only
            - ../../src/infdb-package:/app/mnt/infdb-package
            - /app/.venv # Exclude .venv from volume mount
        extra_hosts:
            - "host.docker.internal:host-gateway"
