services:
    pylovo-generation:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true  # Enable stdin for interactive input
        tty: true         # Allocate a pseudo-TTY
        env_file:
            - ../../.env  # Use root .env file with database credentials
            - env_pylovo.list
        volumes:
            - ../../configs:/app/mnt/configs-infdb #:ro # for root *.yml configs
            - ./configs:/app/configs #:ro # for local pylovo config
            - ../../src/infdb_package:/app/mnt/infdb_package
            - /app/.venv # Exclude .venv from volume mount
        extra_hosts:
            - "host.docker.internal:host-gateway"