services:
  pygeowatch:
    profiles:
      - api
    image: python:3.12-slim # migrate to ghcr.io/astral-sh/uv:python3.12-trixie-slim
    working_dir: /app
    volumes:
      - ./:/app
      - ../../../src/infdb_package:/app/mnt/infdb_package
      - ../../../configs/:/app/mnt/configs-infdb #:ro # for *.yml configs and generated files
      - ./configs:/app/configs #:ro # for configs
    environment:
      PYTHONUNBUFFERED: "1"
    command:
      - /bin/sh
      - -lc
      - >
        python -m pip install --no-cache-dir /app/mnt/infdb_package pyyaml psycopg[binary] && echo "[entrypoint] starting watcher" && exec python -u /app/watch_and_generate_pygeoapi_config.py
    healthcheck:
      test: [ "CMD-SHELL", "test -s /app/pygeoapi-config.yml" ]
      interval: 2s
      timeout: 2s
      retries: 120
      start_period: 2s
    restart: unless-stopped
    networks:
      - infdb_network

  pygeoapi:
    profiles:
      - api
    image: geopython/pygeoapi:latest
    environment:
      PYGEOAPI_CONFIG: /app-config/pygeoapi-config.yml
      CONTAINER_PORT: ${SERVICES_PYGEOAPI_PORT}
    volumes:
      - ./:/app-config:ro
    ports:
      - "${SERVICES_PYGEOAPI_PORT}:${SERVICES_PYGEOAPI_PORT}"
    command: run-with-hot-reload
    depends_on:
      pygeowatch:
        condition: service_healthy
    networks:
      - infdb_network
