services:
    infdb-loader:
        profiles:
            - opendata
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - infdb-loader-data:/workspaces/data
            #- ./configs:/workspaces/infdb-loader/configs:ro  # for production
            - .:/workspaces/infdb-loader # for development only
            - ../../src/infdb_package:/workspaces/infdb_package
            - /workspaces/infdb-loader/.venv # for development only: exclude .venv from volume mount
            - .vscode:/workspaces/.vscode:ro # for development only
            - ../../configs:/workspaces/configs:ro
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - ../../.env
        environment:
            - UV_LINK_MODE=copy

volumes:
    infdb-loader-data:
        name: infdb-loader-data