infdb-postgrest:
    config-infdb: "config-infdb.yml" # only filename - change path in ".env" file "CONFIG_INFDB_PATH"
    logging:
        path: "infdb-postgrest.log"
        level: "INFO" # ERROR, WARNING, INFO, DEBUG
