services:
    jupyter:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /app
        restart: unless-stopped
        ports:
            - "8888:8888"
        volumes:
            - ../../configs:/app/mnt/configs-infdb #:ro # for *.yml configs and generated files
            - ${SERVICES_JUPYTER_PATH_BASE}:/app
            - /app/.venv
        networks:
            - ${BASE_NETWORK_NAME}
        extra_hosts:
            - "host.docker.internal:host-gateway"