services:
    infdb-basedata-buildings:
        build:
            context: .
            dockerfile: Dockerfile
        profiles: 
            - basedata-buildings
        volumes:
            # - ./configs:/workspaces/infdb-basedata-buildings/configs:ro  # for production
            - .:/workspaces/infdb-basedata-buildings # for development only
            - ../../src/infdb_package:/workspaces/infdb_package
            - /workspaces/infdb-basedata-buildings/.venv # Exclude .venv from volume mount
            - .vscode:/workspaces/.vscode:ro
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - ../../.env          # root env (DB creds, CONFIG_INFDB_PATH, etc.)
            - .env                # optional tool-local overrides (if you have any)
        environment:
            - UV_LINK_MODE=copy
