services:
    ro-heat:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./configs:/app/configs #:ro # for configs
            - ./:/app # for development only
            - ../../src/infdb_package:/app/mnt/infdb_package
            - /app/.venv # for development only
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - .env
