services:
    ro-heat:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./configs:/app/configs #:ro # for configs
            - ./:/app # for development only
            - ../../src/infdb_package:/app/mnt/infdb_package
            - /app/.venv # for development only
        extra_hosts:
            - "host.docker.internal:host-gateway"
        # environment:
        #     - AGS: 09780139
        # env_file:
        #     - ro-heat.env
        # depends_on:
        #     infdb-basedata:
        #         condition: service_completed_successfully