services:
    infdb-preprocessor:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ${CONFIG_INFDB_PATH}:/app/mnt/configs-infdb #:ro # for infdb configs
            - ./configs:/app/configs #:ro # for configs
            - .:/app #:ro # for source code # for development only
            - /app/.venv
        extra_hosts:
            - "host.docker.internal:host-gateway"
