services:
    infdb-loader:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - infdb-loader-data:/workspaces/data
            # - ./configs:/workspaces/infdb-loader/configs:ro  # for production
            - .:/workspaces/infdb-loader # for development only
            - ../../src/infdb_package:/workspaces/infdb_package
            - /workspaces/infdb-loader/.venv # Exclude .venv from volume mount
            - .vscode:/workspaces/.vscode:ro
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - .env
            - ${CONFIG_INFDB_ENV_PATH}
        environment:
            - UV_LINK_MODE=copy
        # user: "${UID}:${GID}"

volumes:
    infdb-loader-data:
        # name: infdb-loader-data
        # driver: local
        # driver_opts:
        #     type: none
        #     o: bind
        #     device: ${INFDB_LOADER_DATA_PATH}