services:
    kwp:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./configs:/app/configs #:ro # for configs
            - .:/app/ #:ro # for source code # for development only
            - ../../src/infdb_package:/app/mnt/infdb_package
            - /app/.venv # Exclude .venv from volume mount
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - ${CONFIG_INFDB_ENV_PATH}
            - .env
