# Configuration for the INFDB database setup
# Relative paths are relative to the project directory

base:
    name: neuburg-demo
    path:
        base: "../data/{base/name}/"
    network_name: "infdb-{base/name}_network"
services:
    citydb:
        status: active
        user: citydb_user
        password: infdb
        db: citydb
        host: citydb
        exposed_port: 54329
        epsg: 25832 # 3035 (Europe)
        path: 
            base: "{base/path/base}/citydb/"
            compose_file: "services/3dcitydb/compose.yml"

    timescaledb:
        status: not-active
        user: timescaledb_user
        password: infdb
        db: timescaledb
        host: timescaledb
        exposed_port: 54339
        path: 
            base: "{base/path/base}/timescaledb/"
            compose_file: "services/timescaledb/compose.yml"

    pgadmin:
        default_email: admin@need.energy
        default_password: infdb
        exposed_port: 819
        status: active
        path:
            compose_file: "services/pgadmin/compose.yml"

    api:
        status: active
        port: 8000
        path:
            compose_file: "services/api/fastapi/api.yml"

    pygeoapi:
        status: active
        port: 8001
        path:
            compose_file: "services/api/pygeoapi/pygeoapi.yml"

    postgrest:
        status: active
        port: 8002
        path:
            compose_file: "services/api/postgrest/postgrest.yml"

    jupyter:
        status: active
        exposed_port: 8889
        enable_lab: yes
        token: infdb
        path:
            base: "src/notebooks/"
            compose_file: "services/jupyter/compose.yml"

    qwc:
        status: active
        exposed_port_gui: 809
        exposed_port_db: 54349
        postgres_password: infdb
        path:
            compose_file: "services/qgis_webclient/docker-compose.yml"
