infdb-basedata:
    config-infdb: "config-infdb.yml" # only filename - change path in ".env" file "CONFIG_INFDB_PATH"
    logging:
        path: "infdb-basedata.log"
        level: "INFO" # ERROR, WARNING, INFO, DEBUG
    hosts:
        postgres:
            user: "None"           # Uses SERVICES_POSTGRES_USER from env
            password: "None"       # Uses SERVICES_POSTGRES_PASSWORD from env
            db: "None"             # Uses SERVICES_POSTGRES_DB from env
            host: "None"           # Uses host.docker.internal by default
            exposed_port: "None"   # Uses SERVICES_POSTGRES_EXPOSED_PORT from env
            epsg: "None"           # Uses SERVICES_POSTGRES_EPSG from env
    data:
        input_schema: opendata
        output_schema: basedata #also needs to be changed in env_changelog.list if other than basedata
