ro-heat:
    config-infdb: "config-infdb.yml" # only filename - change path in ".env" file "CONFIG_INFDB_PATH"
    logging:
        path: "ro-heat.log"
        level: "DEBUG" # ERROR, WARNING, INFO, DEBUG
    hosts:
        citydb:
            user: infdb_user
            password: infdb
            db: infdb
            host: ds1.need.energy
            exposed_port: 54328
            epsg: None # 3035 (Europe)
    data:
        input_schema: basedata
        output_schema: ro_heat
