ro-heat:
    config-infdb: "config-infdb.yml" # only filename - change path in ".env" file "CONFIG_INFDB_PATH"
    logging:
        path: "ro-heat.log"
        level: "DEBUG" # ERROR, WARNING, INFO, DEBUG
    hosts:
        postgres:
            user: None
            password: None
            db: infdb
            host: need.energy
            exposed_port: 5432
            epsg: None # 3035 (Europe)
    data:
        input_schema: basedata
        output_schema: ro_heat