services:
  pgrstwatch:
    image: python:3.12-slim
    working_dir: /app
    volumes:
      - .:/app:rw
      - ../../../src/infdb_package:/app/mnt/infdb_package
      - ../../../configs/:/app/mnt/configs-infdb #:ro # for *.yml configs and generated files
      - ./configs:/app/configs #:ro # for configs
    environment:
      PYTHONUNBUFFERED: "1"
    command:
      - /bin/sh
      - -lc
      - >
        python -m pip install --no-cache-dir
        /app/mnt/infdb_package
        psycopg[binary]
        pyyaml
        && echo "[pgrstwatch] starting"
        && exec python -u /app/watch_and_update_postgrest_conf.py
    healthcheck:
      test: ["CMD-SHELL", "test -s /app/postgrest.conf"]
      interval: 5s
      timeout: 5s
      retries: 60
      start_period: 90s
    restart: unless-stopped
    networks:
      - ${BASE_NETWORK_NAME}


  postgrest:
    image: postgrest/postgrest:latest
    command:
      - postgrest
      - /app/postgrest.conf
    volumes:
      - .:/app:ro                           # read-only is fine for PostgREST
    ports:
      - "${SERVICES_POSTGREST_PORT}:${SERVICES_POSTGREST_PORT}"
    depends_on:
      pgrstwatch:
        condition: service_healthy
    networks:
      - ${BASE_NETWORK_NAME}
